# # SQLite. Versions 3.8.0 and up are supported.
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem "sqlite3"
# #
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3




development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: blogs
  pool: 5
  username: root
  password: Panda@120



# production:
#   <<: *default
#   database: <%= ENV['MYSQLDATABASE'] %>
#   username: <%= ENV['MYSQLUSER'] %>
#   password: <%= ENV['MYSQLPASSWORD'] %>
#   host: <%= ENV['MYSQLHOST'] %>
#   port: <%= ENV['MYSQLPORT'] %>









